language: cpp
dist: xenial
cache: False
sudo: False
addons:
  apt:
    packages: 
     - libboost-all-dev
     - libgtest-dev
     - cmake
compiler:
  - clang
  - gcc
script: 
  - mkdir -p build
  - cd build
  - cmake ..
  - make
