language: cpp
dist: xenial
cache: False
addons:
  apt:
    packages: 
     - libboost-all-dev
     - libgtest-dev
     - cmake
compiler:
  - clang
  - gcc
script: 
  - mkdir build_gtest && cd build_gtest && cmake /usr/src/gtest && make && sudo make install
  - mkdir -p build
  - cd build
  - cmake ..
  - make
