language: cpp
dist: trusty
addons:
  apt:
    packages: 
     - libboost-all-dev
     - libgtest-dev
     - cmake
compiler:
  - clang
  - gcc
script: 
  - mkdir -p build
  - cd build
  - cmake ..
  - make
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
